site_name: Trovu
site_url: https://trovu.net

docs_dir: docs
site_dir: dist/public/docs
theme:
  name: material  # Replace with your chosen theme, e.g., 'mkdocs', 'readthedocs', etc.

plugins:
  - search
  - minify:
      minify_html: true

# Navigation structure (if needed)
nav:
  - Home: index.md

Extra options (if needed)
extra:
  social:
    - type: github
      link: https://github.com/trovu/trovu/
