site_name: Trovu
site_description: Search with shortcuts.
site_url: https://trovu.net

docs_dir: docs
site_dir: dist/public/docs
theme:
  name: readthedocs

plugins:
  - search
  - minify:
      minify_html: true

# Navigation structure (if needed)
nav:
  - Home: index.md
  - User guide:
      - users/integration.md
  - Editor guide:
      - editors/policy.md
  - Developer guide:
      - developers/processing.md

extra:
  social:
    - type: github
      link: https://github.com/trovu/trovu/
