site_name: Trovu
site_description: Search with shortcuts.
site_url: https://trovu.net

docs_dir: docs
site_dir: dist/public/docs
theme:
  name: readthedocs

plugins:
  - search
  - minify:
      minify_html: true

# Navigation structure (if needed)
nav:
  - Home: index.md
  - privacy.md
  - User guide:
      - users/processing.md
      - users/integration.md
      - users/advanced.md
      - users/troubleshooting.md
      - users/support.md
  - Shortcuts:
      - shortcuts/namespaces.md
      - shortcuts/urls.md
      - shortcuts/includes.md
      - shortcuts/userscripts.md
  - Editor guide:
      - editors/policy.md
  - Legacy:
      - legacy/differences.md
      - legacy/migrate.md
      - presentations.md

extra:
  social:
    - type: github
      link: https://github.com/trovu/trovu/
