a 0:
  url: http://www.amazon.de/?_encoding=UTF8&camp=1638&creative=6742&linkCode=ur2&site-redirect=at&tag=serchilo-21
  title: Amazon.at Startseite
  tags:
  - amazon
  - shopping
  - books
  - affiliate
a 1:
  url: http://www.amazon.de/gp/search?ie=UTF8&camp=1638&creative=6742&index=aps&keywords={%Suche}&site-redirect=at&linkCode=ur2&tag=serchilo-21
  title: Amazon.at
  tags:
  - amazon
  - shopping
  - books
  - affiliate
  examples:
    goethe: Suche auf Amazon.at nach "goethe"
conrad 0:
  url: http://www.conrad.at/
  title: Conrad Elektronik Österreich
  tags:
  - shopping
  - electronics
  - conrad
conrad 1:
  url: http://www.conrad.at/ce/de/FastSearch.html?search={%Artikel}
  title: Conrad Elektronik Österreich
  tags:
  - shopping
  - electronics
  - conrad
  examples:
    glühlampe: Suche nach Glühlampen
e 0:
  url: https://www.ebay.at/?mkcid=1&mkrid=5221-53469-19255-0&siteid=16&campid=5337375636&customid=&toolid=10001&mkevt=1
  title: Ebay.at
  tags:
  - shopping
  - ebay
  - affiliate
e 1:
  url: https://www.ebay.at/sch/i.html?_from=R40&_trksid=p2380057.m570.l1313&_nkw={%query}&_sacat=0&mkcid=1&mkrid=5221-53469-19255-0&siteid=16&campid=5337375636&customid=&toolid=10001&mkevt=1
  title: Ebay.at
  tags:
  - shopping
  - ebay
  - affiliate
  examples:
    smartphone: Search for "smartphone"
g 1:
  url: https://www.google.at/search?hl={$language}&q={%query}&ie=utf-8
  title: Google.at
  tags:
  - web search
  - google
  examples:
    wien: Google-Suche nach "wien"
gh 0:
  url: http://geizhals.at/
  title: Geizhals Österreich Hauptseite
  tags:
  - geizhals
  - shopping
  - preisvergleich
gh 1:
  url: http://geizhals.at/?fs={%Produkt|encoding=iso-8859-1}
  title: Geizhals Österreich
  tags:
  - geizhals
  - shopping
  - preisvergleich
  examples:
    fernseher: Search for "fernseher"
gm 2:
  url: https://www.google.com/maps/search/{%Stadt|type=city}%2C%20{%Straße}%2C%20Österreich/?hl={$language}
  title: Google Maps Österreich
  tags:
  - maps
  - google
  examples:
    w, praterstern: Zeige Praterstern in Wien
    gd, haupstr.: Zeige Hauptstraße in Gmünd
ikea 0:
  url: http://www.ikea.com/at/de/
  title: IKEA Österreich
  tags:
  - ikea
  - furniture
  - shopping
ikea 1:
  url: http://www.ikea.com/at/de/search/?query={%query}
  title: IKEA Österreich
  tags:
  - ikea
  - furniture
  - shopping
  examples:
    matratze: Suche nach Matratzen
obv 1:
  url: http://search.obvsg.at/primo_library/libweb/action/search.do?dscnt=0&scp.scps=scope%3A%28ACC_aleph%29&frbg=&tab=default_tab&dstmp=1341338980198&srt=rank&ct=search&mode=Basic&dum=true&indx=1&tb=t&vl%28freeText0%29={%query}&fn=search&vid=ACC
  title: OBV Suche - Österreichischer Bibliothekenverbund
  tags:
  - library
  - obv
  examples:
    elfriede jelinek: Suche nach Literatur von und über Elfriede Jelinek
oebb 2:
  url: http://fahrplan.oebb.at/bin/query.exe/dn?S={%Start|type=city}&Z={%Ziel|type=city}&start=1
  title: ÖBB-Auskunft
  tags:
  - bahn
  - travel
  examples:
    wien, salzburg: Verbindung von Wien nach Salzburg
oebb 3:
  url: http://fahrplan.oebb.at/bin/query.exe/dn?S={%Start|type=city}&Z={%Ziel|type=city}&T={%Zeit}&start=1
  title: ÖBB-Auskunft
  tags:
  - bahn
  - travel
  examples:
    wien, salzburg, 10: Verbindung von Wien nach Salzburg um 10:00 Uhr
oebb 4:
  url: http://fahrplan.oebb.at/bin/query.exe/dn?S={%Start|type=city}&Z={%Ziel|type=city}&T={%Zeit}&D={%Datum}&start=1
  title: ÖBB-Auskunft
  tags:
  - bahn
  - travel
  examples:
    wien, salzburg, 10, 1.1.: Verbindung von Wien nach Salzburg um 10:00 Uhr am 1.1.
rsc 1:
  url: http://at.rs-online.com/web/c/?searchTerm={%Produkt}
  title: RS Components Österreich
  tags:
  - shopping
  - electronics
  examples:
    Battery: Suche bei RS Components nach "Battery"
we 0:
  url: http://at.wetter.com/?forcesite=1
  title: Wetter.com
  tags:
  - weather
we 1:
  url: http://at.wetter.com/suche/?search={%Ort}
  title: Wetter.com
  tags:
  - weather
  examples:
    berlin: Search for "berlin"
zal 1:
  url: http://www.zalando.at/katalog/?q={%Produkt}
  title: Zalando.at
  tags:
  - shopping
  - zalando
  examples:
    schuhe: Suche nach Schuhen
öbb 2:
  url: http://fahrplan.oebb.at/bin/query.exe/dn?S={%Start|type=city}&Z={%Ziel|type=city}&start=1
  title: ÖBB-Auskunft
  tags:
  - bahn
  - travel
  examples:
    wien, salzburg: Verbindung von Wien nach Salzburg
öbb 3:
  url: http://fahrplan.oebb.at/bin/query.exe/dn?S={%Start|type=city}&Z={%Ziel|type=city}&T={%Zeit}&start=1
  title: ÖBB-Auskunft
  tags:
  - bahn
  - travel
  examples:
    wien, salzburg, 10: Verbindung von Wien nach Salzburg um 10:00 Uhr
öbb 4:
  url: http://fahrplan.oebb.at/bin/query.exe/dn?S={%Start|type=city}&Z={%Ziel|type=city}&T={%Zeit}&D={%Datum}&start=1
  title: ÖBB-Auskunft
  tags:
  - bahn
  - travel
  examples:
    wien, salzburg, 10, 1.1.: Verbindung von Wien nach Salzburg um 10:00 Uhr am 1.1.
