efr/0:
  url: 'http://www.befr.ebay.be/'
  title: Ebay.be
  description: ''
  tags:
  - shopping
  - ebay
  examples: []
  tests: []
efr/1:
  url: 'http://rover.ebay.com/rover/1/1553-53471-19255-0/1?icep_ff3=9&pub=5575056757&toolid=10001&campid=5337375636&customid=&icep_uq={%query}&icep_sellerId=&icep_ex_kw=&icep_sortBy=12&icep_catId=&icep_minPrice=&icep_maxPrice=&ipn=psmain&icep_vectorid=229522&kwid=902099&mtid=824&kw=lg'
  title: Ebay.be
  description: ''
  tags:
  - shopping
  - ebay
  - affiliate
  examples:
    smartphone: Search for "smartphone"
  tests: []
enl/0:
  url: 'http://www.benl.ebay.be/'
  title: Ebay.be
  description: ''
  tags:
  - shopping
  - ebay
  examples: []
  tests: []
enl/1:
  url: 'http://www.benl.ebay.be//sch/i.html?_nkw={%query}'
  title: Ebay.be
  description: ''
  tags:
  - shopping
  - ebay
  examples:
    smartphone: Search for "smartphone"
  tests: []
g/1:
  url: 'https://www.google.be/search?hl={$language}&q={%query}&ie=utf-8'
  title: Google.be
  description: ''
  tags:
  - web search
  - google
  examples:
    amsterdam: Google zoeken naar "amsterdam"
  tests: []
zal/1:
  url: 'http://www.zalando.be/catalogus/?q={%product}'
  title: Zalando.be
  description: ''
  tags:
  - shopping
  - zalando
  examples:
    schoenen: zoek schoenen
  tests: []
