notbol 1:
  url: http://www.noticiasbolivianas.com/busqueda?searchword={%palabra}&searchphrase=all
  title: Noticias Bolivianas
  tags:
  - news
  - noticias
  - bolivia
  examples:
    deporte: Noticias sobre deporte
