a/1:
  url: 'http://www.amazon.br/s/?field-keywords={%query}'
  title: Amazon.br
  description: ''
  tags:
  - amazon
  - shopping
  - books
  - affiliate
  examples:
    shakespeare: Search for "shakespeare"
  tests: []
