
alza 1:
  url: https://www.alza.cz/search.htm?exps=televizor{%výraz}
  title: Alza.cz
  tags:
  - seznam
  - shopping
  examples:
    televizor: Hledej "televizor"
g 1:
  url: https://www.google.cz/search?hl={$language}&q={%query}&ie=utf-8
  title: Google.cz
  tags:
  - web search
  - google
  examples:
    praha: Hledat "praha" Googlem
idos 2:
  url: http://jizdnirady.idnes.cz/vlakyautobusymhd/spojeni/?f={%odkud|type=city}&t={%kam|type=city}&submit=1&pt=true
  title: IDOS Jízdní řády
  tags:
  - train
  - travel
  - idos
  examples:
    praha, brno: Vlak nebo bus z Prahy do Brna
idos 3:
  url: http://jizdnirady.idnes.cz/vlakyautobusymhd/spojeni/?f={%odkud|type=city}&t={%kam|type=city}&time={%čas|type=time|output=HH:mm}&submit=1&pt=true
  title: IDOS Jízdní řády
  tags:
  - train
  - travel
  - idos
  examples:
    praha, brno, 20: Vlak nebo bus z Prahy do Brna ve 20:00h
idos 4:
  url: http://jizdnirady.idnes.cz/vlakyautobusymhd/spojeni/?f={%odkud|type=city}&t={%kam|type=city}&time={%čas|type=time|output=HH:mm}&date={%datum|type=date|output=DD.MM.YYYY}&submit=1&pt=true
  title: IDOS Jízdní řády
  tags:
  - train
  - travel
  - idos
  examples:
    praha, brno, 20, 10.12.: Vlak nebo bus z Prahy do Brna ve 20:00h v dne 10.12.
ikea 0:
  url: http://www.ikea.com/cz/cs/
  title: IKEA Česká republika
  tags:
  - ikea
  - furniture
  - shopping
  examples:
    matrace: Hledej matrace
ikea 1:
  url: http://www.ikea.com/cz/cs/search/?query={%query}
  title: IKEA Česká republika
  tags:
  - ikea
  - furniture
  - shopping
  examples:
    matrace: Hledej matrace
m 1:
  url: https://mapy.cz/zakladni?q={%místo}
  title: Mapy.cz
  tags:
  - maps
  - mapy
  examples:
    praha: Praha na mapy.cz
mapy 1:
  url: https://mapy.cz/zakladni?q={%místo}
  title: Mapy.cz
  tags:
  - maps
  - mapy
  examples:
    praha: Praha na mapy.cz
seznam 1:
  url: http://search.seznam.cz/search.cgi?w={%query}
  title: Seznam
  tags:
  - seznam
  - web search
  examples:
    praha: Hledej "praha"
tv 0:
  url: http://tvprogram.centrum.cz/
  title: TV programy Česko
  tags:
  - tv
  - centrum
zbozi 1:
  url: https://www.zbozi.cz/hledej/?q={%výraz}
  title: Zboží.cz
  tags:
  - seznam
  - shopping
  examples:
    televizor: Hledej "televizor"
