a 0:
  url: http://www.amazon.es/?_encoding=UTF8&camp=3626&creative=24790&linkCode=ur2&tag=serchilo04-21
  title: Amazon.es
  tags:
  - amazon
  - shopping
  - books
  - affiliate
a 1:
  url: http://www.amazon.es/gp/search?ie=UTF8&camp=3626&creative=24790&index=aps&keywords={%query}&linkCode=ur2&tag=serchilo04-21
  title: Amazon.es
  tags:
  - amazon
  - shopping
  - books
  - affiliate
  examples:
    shakespeare: Search for "shakespeare"
e 0:
  url: https://www.ebay.es/?mkcid=1&mkrid=1185-53479-19255-0&siteid=186&campid=5337375636&customid=&toolid=10001&mkevt=1
  title: Ebay.es
  tags:
  - shopping
  - ebay
  - affiliate
e 1:
  url: https://www.ebay.es/sch/i.html?_from=R40&_trksid=p2380057.m570.l1313&_nkw={%query}&_sacat=0&mkcid=1&mkrid=1185-53479-19255-0&siteid=186&campid=5337375636&customid=&toolid=10001&mkevt=1
  title: Ebay.es
  tags:
  - shopping
  - ebay
  - affiliate
  examples:
    smartphone: Buscar "smartphone" en Ebay
g 1:
  url: https://www.google.es/search?hl={$language}&q={%query}&ie=utf-8
  title: Google.es
  tags:
  - web search
  - google
  examples:
    madrid: Buscar "madrid" con Google
gdfv 2:
  url: http://maps.google.com/maps?hl={$language}&saddr={%start}, Fuerteventura, España&daddr={%destination},
    Fuerteventura, España
  title: Google Maps Directions (Routing), Fuerteventura
  tags:
  - maps
  - google
  - routing
  - route
  - fuerteventura
  examples:
    corralejo, morro jable: Get a route from Corralejo to Morro Jable
gdgc 2:
  url: http://maps.google.com/maps?hl={$language}&saddr={%start}, Gran Canaria, España&daddr={%destination},
    Gran Canaria, España
  title: Google Maps Directions (Routing), Gran Canaria
  tags:
  - maps
  - google
  - routing
  - route
  - gran canaria
  examples:
    las palmas, maspalomas: Get a route from Las Palmas to Maspalomas
gdlz 2:
  url: http://maps.google.com/maps?hl={$language}&saddr={%start}, Lanzarote, España&daddr={%destination},
    Lanzarote, España
  title: Google Maps Directions (Routing), Lanzarote
  tags:
  - maps
  - google
  - routing
  - route
  - lanzarote
  examples:
    arrecife, playa blanca: Get a route from Arrecife to Playa Blanca
gdtf 2:
  url: http://maps.google.com/maps?hl={$language}&saddr={%start}, Tenerife, España&daddr={%destination},
    Tenerife, España
  title: Google Maps Directions (Routing), Tenerife
  tags:
  - maps
  - google
  - routing
  - route
  - tenerife
  examples:
    santa cruz, la laguna: Get a route from Santa Cruz to La Laguna
gma 1:
  url: http://maps.google.com/maps?hl={$language}&q={%dirección}%2C%20Alicante%2C%20Espa%C3%B1a
  title: Google Maps Alicante
  tags:
  - maps
  - google
  examples:
    centro: buscar "centro" en Alicante
gmab 1:
  url: http://maps.google.com/maps?hl={$language}&q={%dirección}%2C%20Albacete%2C%20Espa%C3%B1a
  title: Google Maps Albacete
  tags:
  - maps
  - google
  examples:
    centro: buscar "centro" en Albacete
gmal 1:
  url: http://maps.google.com/maps?hl={$language}&q={%dirección}%2C%20Almer%C3%ADa%2C%20Espa%C3%B1a
  title: Google Maps Almería
  tags:
  - maps
  - google
  examples:
    centro: buscar "centro" en Almería
gmav 1:
  url: http://maps.google.com/maps?hl={$language}&q={%dirección}%2C%20%C3%81vila%2C%20Espa%C3%B1a
  title: Google Maps Ávila
  tags:
  - maps
  - google
  examples:
    centro: buscar "centro" en Ávila
gmb 1:
  url: http://maps.google.com/maps?hl={$language}&q={%dirección}%2C%20Barcelona%2C%20Espa%C3%B1a
  title: Google Maps Barcelona
  tags:
  - maps
  - google
  examples:
    centro: buscar "centro" en Barcelona
gmba 1:
  url: http://maps.google.com/maps?hl={$language}&q={%dirección}%2C%20Badajoz%2C%20Espa%C3%B1a
  title: Google Maps Badajoz
  tags:
  - maps
  - google
  examples:
    centro: buscar "centro" en Badajoz
gmbi 1:
  url: http://maps.google.com/maps?hl={$language}&q={%dirección}%2C%20Bilbao%2C%20Espa%C3%B1a
  title: Google Maps Bilbao
  tags:
  - maps
  - google
  examples:
    centro: buscar "centro" en Bilbao
gmbu 1:
  url: http://maps.google.com/maps?hl={$language}&q={%dirección}%2C%20Burgos%2C%20Espa%C3%B1a
  title: Google Maps Burgos
  tags:
  - maps
  - google
  examples:
    centro: buscar "centro" en Burgos
gmc 1:
  url: http://maps.google.com/maps?hl={$language}&q={%dirección}%2C%20A+Coru%C3%B1a%2C%20Espa%C3%B1a
  title: Google Maps A Coruña
  tags:
  - maps
  - google
  examples:
    centro: buscar "centro" en A Coruña
gmca 1:
  url: http://maps.google.com/maps?hl={$language}&q={%dirección}%2C%20C%C3%A1diz%2C%20Espa%C3%B1a
  title: Google Maps Cádiz
  tags:
  - maps
  - google
  examples:
    centro: buscar "centro" en Cádiz
gmcc 1:
  url: http://maps.google.com/maps?hl={$language}&q={%dirección}%2C%20C%C3%A1ceres%2C%20Espa%C3%B1a
  title: Google Maps Cáceres
  tags:
  - maps
  - google
  examples:
    centro: buscar "centro" en Cáceres
gmce 1:
  url: http://maps.google.com/maps?hl={$language}&q={%dirección}%2C%20Ceuta%2C%20Espa%C3%B1a
  title: Google Maps Ceuta
  tags:
  - maps
  - google
  examples:
    centro: buscar "centro" en Ceuta
gmco 1:
  url: http://maps.google.com/maps?hl={$language}&q={%dirección}%2C%20C%C3%B3rdoba%2C%20Espa%C3%B1a
  title: Google Maps Córdoba
  tags:
  - maps
  - google
  examples:
    centro: buscar "centro" en Córdoba
gmcr 1:
  url: http://maps.google.com/maps?hl={$language}&q={%dirección}%2C%20Ciudad+Real%2C%20Espa%C3%B1a
  title: Google Maps Ciudad Real
  tags:
  - maps
  - google
  examples:
    centro: buscar "centro" en Ciudad Real
gmcs 1:
  url: http://maps.google.com/maps?hl={$language}&q={%dirección}%2C%20Castell%C3%B3n+de+la+Plana%2C%20Espa%C3%B1a
  title: Google Maps Castellón de la Plana
  tags:
  - maps
  - google
  examples:
    centro: buscar "centro" en Castellón de la Plana
gmcu 1:
  url: http://maps.google.com/maps?hl={$language}&q={%dirección}%2C%20Cuenca%2C%20Espa%C3%B1a
  title: Google Maps Cuenca
  tags:
  - maps
  - google
  examples:
    centro: buscar "centro" en Cuenca
gmfv 1:
  url: http://maps.google.com/maps?hl={$language}&q={%dirección}%2C%20Fuerteventura%2C%20Espa%C3%B1a
  title: Google Maps Fuerteventura
  tags:
  - maps
  - google
  examples:
    centro: buscar "centro" en Fuerteventura
gmgc 1:
  url: http://maps.google.com/maps?hl={$language}&q={%dirección}%2C%20Gran+Canaria%2C%20Espa%C3%B1a
  title: Google Maps Gran Canaria
  tags:
  - maps
  - google
  examples:
    centro: buscar "centro" en Gran Canaria
gmgi 1:
  url: http://maps.google.com/maps?hl={$language}&q={%dirección}%2C%20Girona%2C%20Espa%C3%B1a
  title: Google Maps Girona
  tags:
  - maps
  - google
  examples:
    centro: buscar "centro" en Girona
gmgo 1:
  url: http://maps.google.com/maps?hl={$language}&q={%dirección}%2C%20La+Gomera%2C%20Espa%C3%B1a
  title: Google Maps La Gomera
  tags:
  - maps
  - google
  examples:
    centro: buscar "centro" en La Gomera
gmgr 1:
  url: http://maps.google.com/maps?hl={$language}&q={%dirección}%2C%20Granada%2C%20Espa%C3%B1a
  title: Google Maps Granada
  tags:
  - maps
  - google
  examples:
    centro: buscar "centro" en Granada
gmgu 1:
  url: http://maps.google.com/maps?hl={$language}&q={%dirección}%2C%20Guadalajara%2C%20Espa%C3%B1a
  title: Google Maps Guadalajara
  tags:
  - maps
  - google
  examples:
    centro: buscar "centro" en Guadalajara
gmh 1:
  url: http://maps.google.com/maps?hl={$language}&q={%dirección}%2C%20Huelva%2C%20Espa%C3%B1a
  title: Google Maps Huelva
  tags:
  - maps
  - google
  examples:
    centro: buscar "centro" en Huelva
gmhi 1:
  url: http://maps.google.com/maps?hl={$language}&q={%dirección}%2C%20El+Hierro%2C%20Espa%C3%B1a
  title: Google Maps El Hierro
  tags:
  - maps
  - google
  examples:
    centro: buscar "centro" en El Hierro
gmhu 1:
  url: http://maps.google.com/maps?hl={$language}&q={%dirección}%2C%20Huesca%2C%20Espa%C3%B1a
  title: Google Maps Huesca
  tags:
  - maps
  - google
  examples:
    centro: buscar "centro" en Huesca
gmj 1:
  url: http://maps.google.com/maps?hl={$language}&q={%dirección}%2C%20Ja%C3%A9n%2C%20Espa%C3%B1a
  title: Google Maps Jaén
  tags:
  - maps
  - google
  examples:
    centro: buscar "centro" en Jaén
gml 1:
  url: http://maps.google.com/maps?hl={$language}&q={%dirección}%2C%20L%C3%A9rida%2C%20Espa%C3%B1a
  title: Google Maps Lérida
  tags:
  - maps
  - google
  examples:
    centro: buscar "centro" en Lérida
gmle 1:
  url: http://maps.google.com/maps?hl={$language}&q={%dirección}%2C%20Le%C3%B3n%2C%20Espa%C3%B1a
  title: Google Maps León
  tags:
  - maps
  - google
  examples:
    centro: buscar "centro" en León
gmll 1:
  url: http://maps.google.com/maps?hl={$language}&q={%dirección}%2C%20La%20Laguna%2C%20Tenerife%2C%20Espa%C3%B1a
  title: Google Maps La Laguna, Tenerife
  tags:
  - maps
  - google
  examples:
    centro: buscar "centro" en La Laguna
gmlo 1:
  url: http://maps.google.com/maps?hl={$language}&q={%dirección}%2C%20Logro%C3%B1o%2C%20Espa%C3%B1a
  title: Google Maps Logroño
  tags:
  - maps
  - google
  examples:
    centro: buscar "centro" en Logroño
gmlp 1:
  url: http://maps.google.com/maps?hl={$language}&q={%dirección}%2C%20La+Palma%2C%20Espa%C3%B1a
  title: Google Maps La Palma
  tags:
  - maps
  - google
  examples:
    centro: buscar "centro" en La Palma
gmlpgc 1:
  url: http://maps.google.com/maps?hl={$language}&q={%dirección}%2CLas%20Palmas%20de%20Gran%20Canaria%2C%20Espa%C3%B1a
  title: Google Maps Las Palmas de Gran Canaria
  tags:
  - maps
  - google
  examples:
    centro: buscar "centro" en Las Palmas de Gran Canaria
gmlu 1:
  url: http://maps.google.com/maps?hl={$language}&q={%dirección}%2C%20Lugo%2C%20Espa%C3%B1a
  title: Google Maps Lugo
  tags:
  - maps
  - google
  examples:
    centro: buscar "centro" en Lugo
gmlz 1:
  url: http://maps.google.com/maps?hl={$language}&q={%dirección}%2C%20Lanzarote%2C%20Espa%C3%B1a
  title: Google Maps Lanzarote
  tags:
  - maps
  - google
  examples:
    centro: buscar "centro" en Lanzarote
gmm 1:
  url: http://maps.google.com/maps?hl={$language}&q={%dirección}%2C%20Madrid%2C%20Espa%C3%B1a
  title: Google Maps Madrid
  tags:
  - maps
  - google
  examples:
    centro: buscar "centro" en Madrid
gmma 1:
  url: http://maps.google.com/maps?hl={$language}&q={%dirección}%2C%20M%C3%A1laga%2C%20Espa%C3%B1a
  title: Google Maps Málaga
  tags:
  - maps
  - google
  examples:
    centro: buscar "centro" en Málaga
gmml 1:
  url: http://maps.google.com/maps?hl={$language}&q={%dirección}%2C%20Melilla%2C%20Espa%C3%B1a
  title: Google Maps Melilla
  tags:
  - maps
  - google
  examples:
    centro: buscar "centro" en Melilla
gmmu 1:
  url: http://maps.google.com/maps?hl={$language}&q={%dirección}%2C%20Murcia%2C%20Espa%C3%B1a
  title: Google Maps Murcia
  tags:
  - maps
  - google
  examples:
    centro: buscar "centro" en Murcia
gmna 1:
  url: http://maps.google.com/maps?hl={$language}&q={%dirección}%2C%20Navarra%2C%20Espa%C3%B1a
  title: Google Maps Navarra
  tags:
  - maps
  - google
  examples:
    centro: buscar "centro" en Navarra
gmo 1:
  url: http://maps.google.com/maps?hl={$language}&q={%dirección}%2C%20Oviedo%2C%20Espa%C3%B1a
  title: Google Maps Oviedo
  tags:
  - maps
  - google
  examples:
    centro: buscar "centro" en Oviedo
gmou 1:
  url: http://maps.google.com/maps?hl={$language}&q={%dirección}%2C%20Orense%2C%20Espa%C3%B1a
  title: Google Maps Orense
  tags:
  - maps
  - google
  examples:
    centro: buscar "centro" en Orense
gmp 1:
  url: http://maps.google.com/maps?hl={$language}&q={%dirección}%2C%20Palencia%2C%20Espa%C3%B1a
  title: Google Maps Palencia
  tags:
  - maps
  - google
  examples:
    centro: buscar "centro" en Palencia
gmpa 1:
  url: http://maps.google.com/maps?hl={$language}&q={%dirección}%2C%20Pamplona%2C%20Espa%C3%B1a
  title: Google Maps Pamplona
  tags:
  - maps
  - google
  examples:
    centro: buscar "centro" en Pamplona
gmpm 1:
  url: http://maps.google.com/maps?hl={$language}&q={%dirección}%2C%20Palma+de+Mallorca%2C%20Espa%C3%B1a
  title: Google Maps Palma de Mallorca
  tags:
  - maps
  - google
  examples:
    centro: buscar "centro" en Palma de Mallorca
gmpo 1:
  url: http://maps.google.com/maps?hl={$language}&q={%dirección}%2C%20Pontevedra%2C%20Espa%C3%B1a
  title: Google Maps Pontevedra
  tags:
  - maps
  - google
  examples:
    centro: buscar "centro" en Pontevedra
gms 1:
  url: http://maps.google.com/maps?hl={$language}&q={%dirección}%2C%20Santander%2C%20Espa%C3%B1a
  title: Google Maps Santander
  tags:
  - maps
  - google
  examples:
    centro: buscar "centro" en Santander
gmsa 1:
  url: http://maps.google.com/maps?hl={$language}&q={%dirección}%2C%20Salamanca%2C%20Espa%C3%B1a
  title: Google Maps Salamanca
  tags:
  - maps
  - google
  examples:
    centro: buscar "centro" en Salamanca
gmsctf 1:
  url: http://maps.google.com/maps?hl={$language}&q={%dirección}%2C%20Santa%20Cruz%20de%20Tenerife%2C%20Espa%C3%B1a
  title: Google Maps Santa Cruz de Tenerife
  tags:
  - maps
  - google
  examples:
    centro: buscar "centro" en Santa Cruz de Tenerife
gmse 1:
  url: http://maps.google.com/maps?hl={$language}&q={%dirección}%2C%20Sevilla%2C%20Espa%C3%B1a
  title: Google Maps Sevilla
  tags:
  - maps
  - google
  examples:
    centro: buscar "centro" en Sevilla
gmsg 1:
  url: http://maps.google.com/maps?hl={$language}&q={%dirección}%2C%20Segovia%2C%20Espa%C3%B1a
  title: Google Maps Segovia
  tags:
  - maps
  - google
  examples:
    centro: buscar "centro" en Segovia
gmso 1:
  url: http://maps.google.com/maps?hl={$language}&q={%dirección}%2C%20Soria%2C%20Espa%C3%B1a
  title: Google Maps Soria
  tags:
  - maps
  - google
  examples:
    centro: buscar "centro" en Soria
gmss 1:
  url: http://maps.google.com/maps?hl={$language}&q={%dirección}%2C%20San+Sebasti%C3%A1n%2C%20Espa%C3%B1a
  title: Google Maps San Sebastián
  tags:
  - maps
  - google
  examples:
    centro: buscar "centro" en San Sebastián
gmt 1:
  url: http://maps.google.com/maps?hl={$language}&q={%dirección}%2C%20Tarragona%2C%20Espa%C3%B1a
  title: Google Maps Tarragona
  tags:
  - maps
  - google
  examples:
    centro: buscar "centro" en Tarragona
gmte 1:
  url: http://maps.google.com/maps?hl={$language}&q={%dirección}%2C%20Teruel%2C%20Espa%C3%B1a
  title: Google Maps Teruel
  tags:
  - maps
  - google
  examples:
    centro: buscar "centro" en Teruel
gmtf 1:
  url: http://maps.google.com/maps?hl={$language}&q={%dirección}%2C%20Tenerife%2C%20Espa%C3%B1a
  title: Google Maps Tenerife
  tags:
  - maps
  - google
  examples:
    centro: buscar "centro" en Tenerife
gmto 1:
  url: http://maps.google.com/maps?hl={$language}&q={%dirección}%2C%20Toledo%2C%20Espa%C3%B1a
  title: Google Maps Toledo
  tags:
  - maps
  - google
  examples:
    centro: buscar "centro" en Toledo
gmv 1:
  url: http://maps.google.com/maps?hl={$language}&q={%dirección}%2C%20Valencia%2C%20Espa%C3%B1a
  title: Google Maps Valencia
  tags:
  - maps
  - google
  examples:
    centro: buscar "centro" en Valencia
gmva 1:
  url: http://maps.google.com/maps?hl={$language}&q={%dirección}%2C%20Valladolid%2C%20Espa%C3%B1a
  title: Google Maps Valladolid
  tags:
  - maps
  - google
  examples:
    centro: buscar "centro" en Valladolid
gmvi 1:
  url: http://maps.google.com/maps?hl={$language}&q={%dirección}%2C%20Vitoria%2C%20Espa%C3%B1a
  title: Google Maps Vitoria
  tags:
  - maps
  - google
  examples:
    centro: buscar "centro" en Vitoria
gmz 1:
  url: http://maps.google.com/maps?hl={$language}&q={%dirección}%2C%20Zaragoza%2C%20Espa%C3%B1a
  title: Google Maps Zaragoza
  tags:
  - maps
  - google
  examples:
    centro: buscar "centro" en Zaragoza
gmza 1:
  url: http://maps.google.com/maps?hl={$language}&q={%dirección}%2C%20Zamora%2C%20Espa%C3%B1a
  title: Google Maps Zamora
  tags:
  - maps
  - google
  examples:
    centro: buscar "centro" en Zamora
ikea 0:
  url: http://www.ikea.com/es/es/
  title: IKEA España
  tags:
  - ikea
  - furniture
  - shopping
ikea 1:
  url: http://www.ikea.com/es/es/search/?query={%query}
  title: IKEA España
  tags:
  - ikea
  - furniture
  - shopping
  examples:
    colchón: Buscar colchón
ma 1:
  url: https://www.milanuncios.com/anuncios/{%query}.htm?fromSearch=1
  title: Milanuncios
  description: venta de productos de segunda mano
  tags:
  - shopping
  - segunda mano
  examples:
    palmera: Busqueda de "palmera"
mil 0:
  url: http://www.milanuncios.com/
  title: Mil Anuncios
  tags:
  - shopping
  - ads
  - anuncios
mil 1:
  url: http://www.milanuncios.com/anuncios/{%query}.htm
  title: Mil Anuncios
  tags:
  - shopping
  - ads
  - anuncios
  examples:
    bicicleteas en madrid: Buscar bicicleteas en madrid
titsa 2:
  url: https://www.google.com/maps?hl={$language}&saddr={%origen},%20Tenerife,+Espa%C3%B1a&daddr={%destino},%20Tenerife,%20Espa%C3%B1a&f=d&dirflg=r
  title: Transportes Interurbanos de Tenerife
  tags:
  - tenerife
  - titsa
  - travel
  - google
  - maps
  examples:
    weyler, trinidad: Próxima connection de Weyler a Trinidad
titsa 3:
  url: https://www.google.com/maps?hl={$language}&saddr={%origen},%20Tenerife,+Espa%C3%B1a&daddr={%destino},%20Tenerife,%20Espa%C3%B1a&time={%salida}&f=d&dirflg=r
  title: Transportes Interurbanos de Tenerife
  tags:
  - tenerife
  - titsa
  - travel
  - google
  - maps
  examples:
    weyler, trinidad, 10: Connection de Weyler a Trinidad a las 10
zal 1:
  url: http://www.zalando.es/catalogo/?q={%product}
  title: Zalando.es
  tags:
  - shopping
  - zalando
  examples:
    calzado: buscar calzado
