reitti/2:
  url: 'http://www.reittiopas.fi/?showsearchformsaved=hide&from_in={%from}&to_in={%to}'
  title: Reittiopas Helsingin seudun liikenne
  description: ''
  tags:
  - travel
  - helsinki
  examples:
    'Kumpulan Kampus, Rautatientori': Next connection from Kumpulan Kampus to Rautatientori
  tests: []
reitti/4:
  url: 'http://www.reittiopas.fi/?from_in={%from}&to_in={%to}&hour={%hour}&minute={%minute}'
  title: Reittiopas Helsingin seudun liikenne
  description: ''
  tags:
  - travel
  - helsinki
  examples:
    'Ruoholahti, Itäkeskus, 13, 37': 'Find public transit connections from Ruoholahti to Itäkeskus at 13:37'
  tests: []
zal/1:
  url: 'http://www.zalando.fi/katalogi/?q={%tavara}'
  title: Zalando.fi
  description: ''
  tags:
  - shopping
  - zalando
  examples:
    jalkine: search for "jalkine"
  tests: []
