a/0:
  url: 'http://www.amazon.co.uk/?_encoding=UTF8&camp=1634&creative=6738&linkCode=ur2&tag=serchilo02-21'
  title: Amazon.co.uk Homepage
  description: ''
  tags:
  - amazon
  - shopping
  - books
  - affiliate
  examples: []
  tests: []
a/1:
  url: 'http://www.amazon.co.uk/gp/search?ie=UTF8&camp=1634&creative=6738&index=aps&keywords={%query|encoding=iso-8859-1}&linkCode=ur2&tag=serchilo02-21'
  title: Amazon.co.uk
  description: ''
  tags:
  - amazon
  - shopping
  - books
  - affiliate
  examples:
    shakespeare: Search for "shakespeare"
  tests: []
e/0:
  url: 'http://rover.ebay.com/rover/1/710-53481-19255-0/1?icep_ff3=1&pub=5575056757&toolid=10001&campid=5337375636&customid=&ipn=psmain&icep_vectorid=229508&kwid=902099&mtid=824&kw=lg'
  title: Ebay.co.uk
  description: ''
  tags:
  - shopping
  - ebay
  - affiliate
  examples: []
  tests: []
e/1:
  url: 'http://rover.ebay.com/rover/1/710-53481-19255-0/1?icep_ff3=9&pub=5575056757&toolid=10001&campid=5337375636&customid=&icep_uq={%query}&icep_sellerId=&icep_ex_kw=&icep_sortBy=12&icep_catId=&icep_minPrice=&icep_maxPrice=&ipn=psmain&icep_vectorid=229508&kwid=902099&mtid=824&kw=lg'
  title: Ebay.co.uk
  description: ''
  tags:
  - shopping
  - ebay
  - affiliate
  examples:
    smartphone: Search for "smartphone"
  tests: []
g/1:
  url: 'https://www.google.co.uk/search?hl={$language}&q={%query}&ie=utf-8'
  title: Google.co.uk
  description: ''
  tags:
  - web search
  - google
  examples:
    london: Search Google for "london"
  tests: []
tfl/2:
  url: >-
    http://journeyplanner.tfl.gov.uk/user/XSLT_TRIP_REQUEST2?language=en&sessionID=0&requestID=0&ptOptionsActive=1&itOptionsActive=1&imparedOptionsActive=1&ptAdvancedOptions=1&advOptActive_2=1&advOpt_2=1&execInst=normal&command=&itdLPxx_request=&itdLPxx_view=&itdLPxx_tubeMap=&calculateDistance=1&imageFormat=png|pdf&imageOnly=1&imageWidth=705&imageHeight=500&tt_valid_until=20131223&name_origin={%from}&nameState_origin=notidentified&nameDefaultText_origin=Enter+start+location...&type_origin=stop&place_origin=London&name_destination={%to}&nameState_destination=notidentified&nameDefaultText_destination=Enter+end+location...&type_destination=stop&place_destination=London&placeDefaultText_via=London&name_via=Enter+location...&nameState_via=notidentified&nameDefaultText_via=Enter+location...&type_via=stop&place_via=London&itdTripDateTimeDepArr=dep&stepfree-access=no-requirements&routeType=LEASTTIME&includedMeans=checkbox&inclMOT_11=on&inclMOT_2=on&inclMOT_1=on&inclMOT_5=on&inclMOT_0=on&inclMOT_4=on&inclMOT_9=on&inclMOT_7=on&inclMOT_8=on&inclMOT_3=on&trITMOTvalue=20&trITMOT=100&changeSpeed=normal
  title: Transport for London
  description: ''
  tags:
  - travel
  - transport
  - london
  examples:
    'brixton, paddington': Search the next connection from Brixton to Paddington
  tests: []
tfl/3:
  url: >-
    http://journeyplanner.tfl.gov.uk/user/XSLT_TRIP_REQUEST2?language=en&sessionID=0&requestID=0&ptOptionsActive=1&itOptionsActive=1&imparedOptionsActive=1&ptAdvancedOptions=1&advOptActive_2=1&advOpt_2=1&execInst=normal&command=&itdLPxx_request=&itdLPxx_view=&itdLPxx_tubeMap=&calculateDistance=1&imageFormat=png|pdf&imageOnly=1&imageWidth=705&imageHeight=500&tt_valid_until=20131223&name_origin={%from}&nameState_origin=notidentified&nameDefaultText_origin=Enter+start+location...&type_origin=stop&place_origin=London&name_destination={%to}&nameState_destination=notidentified&nameDefaultText_destination=Enter+end+location...&type_destination=stop&place_destination=London&placeDefaultText_via=London&name_via=Enter+location...&nameState_via=notidentified&nameDefaultText_via=Enter+location...&type_via=stop&place_via=London&itdTripDateTimeDepArr=dep&stepfree-access=no-requirements&routeType=LEASTTIME&includedMeans=checkbox&inclMOT_11=on&inclMOT_2=on&inclMOT_1=on&inclMOT_5=on&inclMOT_0=on&inclMOT_4=on&inclMOT_9=on&inclMOT_7=on&inclMOT_8=on&inclMOT_3=on&trITMOTvalue=20&trITMOT=100&changeSpeed=normal&itdTime={%hour}:00
  title: Transport for London
  description: ''
  tags:
  - travel
  - transport
  - london
  examples:
    'brixton, paddington, 10': 'Search the next connection from Brixton to Paddington at 10:00'
  tests: []
tl/2:
  url: 'https://www.thetrainline.com/buytickets/combinedmatrix.aspx?Command=TimeTable#Journey/{%from}/{%to}/{$now|output=DD/MM/YY/HH/mm}/Leave%20After//////Leave%20After/1/0//'
  title: thetrainline.com
  description: ''
  tags:
  - travel
  - transport
  examples:
    'manchester, london': Search for trains from Manchester to London
  tests: []
tl/4:
  url: 'https://www.thetrainline.com/buytickets/combinedmatrix.aspx?Command=TimeTable#Journey/{%from}/{%to}/{%date}/{%time}/Leave%20After//////Leave%20After/1/0//'
  title: thetrainline.com
  description: ''
  tags:
  - travel
  - transport
  examples:
    'manchester, london, 22/06/16, 14/30': Search for trains from Manchester to London
  tests: []
tv/0:
  url: 'http://www.tvguide.co.uk/'
  title: tvguide.co.uk
  description: ''
  tags:
  - tv
  examples: []
  tests: []
zal/1:
  url: 'http://www.zalando.co.uk/catalog/?q={%product}'
  title: Zalando.co.uk
  description: ''
  tags:
  - shopping
  - zalando
  examples:
    shoes: search for shoes
  tests: []
