e 0:
  url: https://www.ebay.com.hk
  title: Ebay.com.hk
  tags:
  - ebay
  - shopping
e 1:
  url: http://www.ebay.com.hk/sch/i.html?_nkw={%query}
  title: Ebay.com.hk
  tags:
  - ebay
  - shopping
  examples:
    smartphone: Search for "smartphone"
