e 0:
  url: http://rover.ebay.com/rover/1/5282-53468-19255-0/1?icep_ff3=1&pub=5575056757&toolid=10001&campid=5337375636&customid=&ipn=psmain&icep_vectorid=229543&kwid=902099&mtid=824&kw=lg
  title: Ebay.ie
  tags:
  - shopping
  - ebay
  - affiliate
e 1:
  url: http://rover.ebay.com/rover/1/5282-53468-19255-0/1?icep_ff3=9&pub=5575056757&toolid=10001&campid=5337375636&customid=&icep_uq={%query}&icep_sellerId=&icep_ex_kw=&icep_sortBy=12&icep_catId=&icep_minPrice=&icep_maxPrice=&ipn=psmain&icep_vectorid=229543&kwid=902099&mtid=824&kw=lg
  title: Ebay.ie
  tags:
  - shopping
  - ebay
  - affiliate
  examples:
    smartphone: Search for "smartphone"
g 1:
  url: https://www.google.ie/search?hl={$language}&q={%query}&ie=utf-8
  title: Google.ie
  tags:
  - web search
  - google
  examples:
    dublin: Search Google for "dublin"
gmc 1:
  url: http://maps.google.com/maps?hl={$language}&q={%address}%2C%20Cork%2C%20Ireland
  title: Google Maps Cork
  tags:
  - maps
  - google
  examples:
    main st: Show Main Street in Cork
gmce 1:
  url: http://maps.google.com/maps?hl={$language}&q={%address}%2C%20Clare%2C%20Ireland
  title: Google Maps Clare
  tags:
  - maps
  - google
  examples:
    main st: Show Main Street in Clare
gmcn 1:
  url: http://maps.google.com/maps?hl={$language}&q={%address}%2C%20Cavan%2C%20Ireland
  title: Google Maps Cavan
  tags:
  - maps
  - google
  examples:
    main st: Show Main Street in Cavan
gmcw 1:
  url: http://maps.google.com/maps?hl={$language}&q={%address}%2C%20Carlow%2C%20Ireland
  title: Google Maps Carlow
  tags:
  - maps
  - google
  examples:
    main st: Show Main Street in Carlow
gmd 1:
  url: http://maps.google.com/maps?hl={$language}&q={%address}%2C%20Dublin%2C%20Ireland
  title: Google Maps Dublin
  tags:
  - maps
  - google
  examples:
    main st: Show Main Street in Dublin
gmdl 1:
  url: http://maps.google.com/maps?hl={$language}&q={%address}%2C%20Donegal%2C%20Ireland
  title: Google Maps Donegal
  tags:
  - maps
  - google
  examples:
    main st: Show Main Street in Donegal
gmg 1:
  url: http://maps.google.com/maps?hl={$language}&q={%address}%2C%20Galway%2C%20Ireland
  title: Google Maps Galway
  tags:
  - maps
  - google
  examples:
    main st: Show Main Street in Galway
gmke 1:
  url: http://maps.google.com/maps?hl={$language}&q={%address}%2C%20Kildare%2C%20Ireland
  title: Google Maps Kildare
  tags:
  - maps
  - google
  examples:
    main st: Show Main Street in Kildare
gmkk 1:
  url: http://maps.google.com/maps?hl={$language}&q={%address}%2C%20Kilkenny%2C%20Ireland
  title: Google Maps Kilkenny
  tags:
  - maps
  - google
  examples:
    main st: Show Main Street in Kilkenny
gmky 1:
  url: http://maps.google.com/maps?hl={$language}&q={%address}%2C%20Kerry%2C%20Ireland
  title: Google Maps Kerry
  tags:
  - maps
  - google
  examples:
    main st: Show Main Street in Kerry
gml 1:
  url: http://maps.google.com/maps?hl={$language}&q={%address}%2C%20Limerick%2C%20Ireland
  title: Google Maps Limerick
  tags:
  - maps
  - google
  examples:
    main st: Show Main Street in Limerick
gmld 1:
  url: http://maps.google.com/maps?hl={$language}&q={%address}%2C%20Longford%2C%20Ireland
  title: Google Maps Longford
  tags:
  - maps
  - google
  examples:
    main st: Show Main Street in Longford
gmlh 1:
  url: http://maps.google.com/maps?hl={$language}&q={%address}%2C%20Louth%2C%20Ireland
  title: Google Maps Louth
  tags:
  - maps
  - google
  examples:
    main st: Show Main Street in Louth
gmlm 1:
  url: http://maps.google.com/maps?hl={$language}&q={%address}%2C%20Leitrim%2C%20Ireland
  title: Google Maps Leitrim
  tags:
  - maps
  - google
  examples:
    main st: Show Main Street in Leitrim
gmls 1:
  url: http://maps.google.com/maps?hl={$language}&q={%address}%2C%20Laois%2C%20Ireland
  title: Google Maps Laois
  tags:
  - maps
  - google
  examples:
    main st: Show Main Street in Laois
gmmh 1:
  url: http://maps.google.com/maps?hl={$language}&q={%address}%2C%20Meath%2C%20Ireland
  title: Google Maps Meath
  tags:
  - maps
  - google
  examples:
    main st: Show Main Street in Meath
gmmn 1:
  url: http://maps.google.com/maps?hl={$language}&q={%address}%2C%20Monaghan%2C%20Ireland
  title: Google Maps Monaghan
  tags:
  - maps
  - google
  examples:
    main st: Show Main Street in Monaghan
gmmo 1:
  url: http://maps.google.com/maps?hl={$language}&q={%address}%2C%20Mayo%2C%20Ireland
  title: Google Maps Mayo
  tags:
  - maps
  - google
  examples:
    main st: Show Main Street in Mayo
gmoy 1:
  url: http://maps.google.com/maps?hl={$language}&q={%address}%2C%20Offaly%2C%20Ireland
  title: Google Maps Offaly
  tags:
  - maps
  - google
  examples:
    main st: Show Main Street in Offaly
gmrn 1:
  url: http://maps.google.com/maps?hl={$language}&q={%address}%2C%20Roscommon%2C%20Ireland
  title: Google Maps Roscommon
  tags:
  - maps
  - google
  examples:
    main st: Show Main Street in Roscommon
gmso 1:
  url: http://maps.google.com/maps?hl={$language}&q={%address}%2C%20Sligo%2C%20Ireland
  title: Google Maps Sligo
  tags:
  - maps
  - google
  examples:
    main st: Show Main Street in Sligo
gmt 1:
  url: http://maps.google.com/maps?hl={$language}&q={%address}%2C%20Tipperary%2C%20Ireland
  title: Google Maps Tipperary
  tags:
  - maps
  - google
  examples:
    main st: Show Main Street in Tipperary
gmw 1:
  url: http://maps.google.com/maps?hl={$language}&q={%address}%2C%20Waterford%2C%20Ireland
  title: Google Maps Waterford
  tags:
  - maps
  - google
  examples:
    main st: Show Main Street in Waterford
gmwh 1:
  url: http://maps.google.com/maps?hl={$language}&q={%address}%2C%20Westmeath%2C%20Ireland
  title: Google Maps Westmeath
  tags:
  - maps
  - google
  examples:
    main st: Show Main Street in Westmeath
gmww 1:
  url: http://maps.google.com/maps?hl={$language}&q={%address}%2C%20Wicklow%2C%20Ireland
  title: Google Maps Wicklow
  tags:
  - maps
  - google
  examples:
    main st: Show Main Street in Wicklow
gmwx 1:
  url: http://maps.google.com/maps?hl={$language}&q={%address}%2C%20Wexford%2C%20Ireland
  title: Google Maps Wexford
  tags:
  - maps
  - google
  examples:
    main st: Show Main Street in Wexford
luas 1:
  url: https://www.google.com/search?hl={$language}&ie=utf-8&btnI=1&q=site%3Awww.luas.ie%20{%station}
  title: Luas Dublin Light Rail
  tags:
  - travel
  - dublin
  examples:
    harcourt: show next trams from Harcourt station
