a/1:
  url: 'http://www.amazon.in/s/?field-keywords={%query}'
  title: Amazon.in
  tags:
  - amazon
  - shopping
  - books
  - affiliate
  examples:
    shakespeare: Search for "shakespeare"
e/0:
  url: 'http://www.ebay.in/'
  title: Ebay.in
  tags:
  - shopping
  - ebay
e/1:
  url: 'http://www.ebay.in/sch/i.html?_nkw={%query}'
  title: Ebay.in
  tags:
  - shopping
  - ebay
  examples:
    smartphone: Search for "smartphone"
