e/0:
  url: 'http://www.ebay.com.my/'
  title: Ebay.com.my
  description: ''
  tags:
  - shopping
  - ebay
  examples: []
  tests: []
e/1:
  url: 'http://www.ebay.com.my/sch/i.html?_nkw={%query}'
  title: Ebay.com.my
  description: ''
  tags:
  - shopping
  - ebay
  examples:
    smartphone: Search for "smartphone"
  tests: []
