al 0:
  url: https://allegro.pl/
  title: Allegro
  tags:
  - shopping
  - allegro
al 1:
  url: https://allegro.pl/listing?string={%przedmiot}
  title: Allegro
  tags:
  - shopping
  - allegro
  examples:
    smartfon: szukaj "smartfon"
ceneo 0:
  url: http://www.ceneo.pl/
  title: Ceneo
  tags:
  - shopping
ceneo 1:
  url: http://www.ceneo.pl/categories.aspx?search=yes&categoryID=0&searchText={%produkt}&inDesc=False&minPrice=0&maxPrice=99999999
  title: Ceneo
  tags:
  - shopping
  examples:
    iphone: ceny iPhone'a
e 0:
  url: http://www.ebay.pl/
  title: Ebay.pl
  tags:
  - shopping
  - ebay
e 1:
  url: http://www.ebay.pl/sch/i.html?_nkw={%query}
  title: Ebay.pl
  tags:
  - shopping
  - ebay
  examples:
    smartphone: Search for "smartphone"
ep 2:
  url: http://www.e-podroznik.pl/public/searcherFinal.do?lang=pl&method=plain&formCompositeSearcherFinal.fromText={%start}&formCompositeSearcherFinal.toText={%cel}
  title: e-podróżnik.pl
  tags:
  - travel
  - railway
  - pkp
  - e-podróżnik
  examples:
    kutno, gniezno: połączenie z Kutna do Gniezna
ep 3:
  url: http://www.e-podroznik.pl/public/searcherFinal.do?lang=pl&method=plain&formCompositeSearcherFinal.fromText={%start}&formCompositeSearcherFinal.toText={%cel}&formCompositeSearcherFinal.time={%czas}
  title: e-podróżnik.pl
  tags:
  - travel
  - railway
  - pkp
  - e-podróżnik
  examples:
    kutno, gniezno, 10: połączenie z Kutna do Gniezna o godz. 10
ep 4:
  url: http://www.e-podroznik.pl/public/searcherFinal.do?lang=pl&method=plain&formCompositeSearcherFinal.fromText={%start}&formCompositeSearcherFinal.toText={%cel}&formCompositeSearcherFinal.time={%czas}&formCompositeSearcherFinal.date={%data}
  title: e-podróżnik.pl
  tags:
  - travel
  - railway
  - pkp
  - e-podróżnik
  examples:
    kutno, gniezno, 10, 31.1.13: połączenie z Kutna do Gniezna 31 stycznia 2013 o godz. 10
g 1:
  url: https://www.google.pl/search?hl={$language}&q={%query}&ie=utf-8
  title: Google.pl
  tags:
  - web search
  - google
  examples:
    warszawa: Szukaj "warszawa" w Google.pl
gastro 2:
  url: http://www.gastronauci.pl/pl/restauracje/{%miasto}?kind={%lokal/kuchnia}
  title: gastronauci.pl
  tags:
  - food
  - restaurant
  examples:
    warszawa, bar mleczny: bary mleczne w Warszawie
gm 2:
  url: https://www.google.com/maps/search/{%miasto|type=city}%2C%20{%adres}%2C%20Polska/?hl={$language}
  title: Google Maps Polska
  tags:
  - maps
  - google
  examples:
    w, rynek: Pokaż rynek w Warszawie
    dw, rynek: Pokaż rynek we Wrocławiu
ikea 0:
  url: http://www.ikea.com/pl/pl/
  title: IKEA Polska
  tags:
  - ikea
  - furniture
  - shopping
ikea 1:
  url: http://www.ikea.com/pl/pl/search/?query={%query}
  title: IKEA Polska
  tags:
  - ikea
  - furniture
  - shopping
  examples:
    materac: Szukaj materace
jddw 2:
  url: http://jakdojade.pl?cid=2000&fn={%start}&tn={%cel}&as=true
  title: jakdojade.pl, Wrocław
  tags:
  - travel
  - jakdojade
  - wrocław
  examples:
    rynek, dworzec gł: połączenie z Rynka do Dworca Głównego
jddw 3:
  url: http://jakdojade.pl?cid=2000&fn={%start}&tn={%cel}&h={%czas}&as=true
  title: jakdojade.pl, Wrocław
  tags:
  - travel
  - jakdojade
  - wrocław
  examples:
    rynek, dworzec gł, 10: połączenie z Rynka do Dworca Głównego o godz. 10
jddw 4:
  url: http://jakdojade.pl?cid=2000&fn={%start}&tn={%cel}&h={%czas}&d={%dzień}&as=true
  title: jakdojade.pl, Wrocław
  tags:
  - travel
  - jakdojade
  - wrocław
  examples:
    rynek, dworzec gł, 10, 31.12.13: połączenie z Rynka do Dworca Głównego 31 grudnia 2013 o godz. 10
jdpo 2:
  url: http://jakdojade.pl?cid=1000&fn={%start}&tn={%cel}&as=true
  title: jakdojade.pl, Poznań
  tags:
  - travel
  - jakdojade
  - poznań
  examples:
    rynek, dworzec gł: połączenie z Rynka do Dworca Głównego
jdpo 3:
  url: http://jakdojade.pl?cid=1000&fn={%start}&tn={%cel}&h={%czas}&as=true
  title: jakdojade.pl, Poznań
  tags:
  - travel
  - jakdojade
  - poznań
  examples:
    rynek, dworzec gł, 10: połączenie z Rynka do Dworca Głównego o godz. 10
jdpo 4:
  url: http://jakdojade.pl?cid=1000&fn={%start}&tn={%cel}&h={%czas}&d={%dzień}&as=true
  title: jakdojade.pl, Poznań
  tags:
  - travel
  - jakdojade
  - poznań
  examples:
    rynek, dworzec gł, 10, 31.12.13: połączenie z Rynka do Dworca Głównego 31 grudnia 2013 o godz. 10
jdw 2:
  url: http://jakdojade.pl?cid=3000&fn={%start}&tn={%cel}&as=true
  title: jakdojade.pl, Warszawa
  tags:
  - travel
  - jakdojade
  - warszawa
  examples:
    stare miasto, centrum: połączenie ze Starego miasta do Centrum
jdw 3:
  url: http://jakdojade.pl?cid=3000&fn={%start}&tn={%cel}&h={%czas}&as=true
  title: jakdojade.pl, Warszawa
  tags:
  - travel
  - jakdojade
  - warszawa
  examples:
    stare miasto, centrum, 10: połączenie ze Starego miasta do Centrum o godz. 10
jdw 4:
  url: http://jakdojade.pl?cid=3000&fn={%start}&tn={%cel}&h={%czas}&d={%dzień}&as=true
  title: jakdojade.pl, Warszawa
  tags:
  - travel
  - jakdojade
  - warszawa
  examples:
    stare miasto, centrum, 10, 31.12.13: połączenie ze Starego miasta do Centrum 31 grudnia 2013 o godz. 10
nk 0:
  url: http://nk.pl/
  title: Nasza Klasa
  tags:
  - social network
  - nasza klasa
nk 1:
  url: http://nk.pl/#szukaj#{%nazwisko / grupa}
  title: Nasza Klasa
  tags:
  - social network
  - nasza klasa
  examples:
    kowalski: Szukaj "kowalski"
pkp 2:
  url: http://rozklad-pkp.pl/pl/tp?S={%start|type=city}&Z={%cel|type=city}&start=1&queryPageDisplayed=yes
  title: PKP rozkład jazdy
  tags:
  - travel
  - railway
  - pkp
  examples:
    kutno, gniezno: następne połączenie PKP z Kutna do Gniezna
    w, p: następne połączenie z Warszawy do Poznania
    gdansk!, wroclaw!: następne połączenie ze Szczecina do Wrocławia, automatycznie wybierz Gdańsk Głowny i Wrocław Głowny
pkp 3:
  url: http://rozklad-pkp.pl/pl/tp?S={%start|type=city}&Z={%cel|type=city}&T={%czas|type=time|output=HH:mm}&start=1&queryPageDisplayed=yes
  title: PKP rozkład jazdy
  tags:
  - travel
  - railway
  - pkp
  examples:
    kutno, gniezno, 10: połączenie z Kutna do Gniezna dzisiaj o godz. 10
pkp 4:
  url: http://rozklad-pkp.pl/pl/tp?S={%start|type=city}&Z={%cel|type=city}&T={%czas|type=time|output=HH:mm}&D={%data|type=date|output=DD.MM.YYYY}&start=1&queryPageDisplayed=yes
  title: PKP rozkład jazdy
  tags:
  - travel
  - railway
  - pkp
  examples:
    kutno, gniezno, 10, 31.1.: połączenie z Kutna do Gniezna 31 stycznia o godz. 10
tm 1:
  url: http://www.google.com/search?hl={$language}&sitesearch=teleman.pl&domains=teleman.pl&q={%szukaj}
  title: teleman.pl program telewizyjny
  tags:
  - tv
  - polska
  - poland
  examples:
    tvn: Szukaj programy TVN
zal 1:
  url: http://www.zalando.pl/katalog/?q={%produkt}
  title: Zalando.pl
  tags:
  - shopping
  - zalando
  examples:
    buty: Szukaj buty
