blocket/1:
  url: 'http://www.blocket.se/li?q={%query}'
  title: Blocket.se
  tags:
  - shopping
  - blocket
  examples:
    iphone: Search for "iphone"
e/0:
  url: 'http://www.ebay.se/'
  title: Ebay.se
  tags:
  - shopping
  - ebay
e/1:
  url: 'http://www.ebay.se/sch/i.html?_nkw={%query}'
  title: Ebay.se
  tags:
  - shopping
  - ebay
  examples:
    smartphone: Search for "smartphone"
gma/1:
  url: 'http://maps.google.com/maps?hl={$language}&q={%adress}%2C%20Alings%C3%A5s%2C%20Sverige'
  title: Google Maps Alingsås
  tags:
  - maps
  - google
  examples:
    centrum: sök centrum i Alingsås
gmb/1:
  url: 'http://maps.google.com/maps?hl={$language}&q={%adress}%2C%20Bor%C3%A5s%2C%20Sverige'
  title: Google Maps Borås
  tags:
  - maps
  - google
  examples:
    centrum: sök centrum i Borås
gmbl/1:
  url: 'http://maps.google.com/maps?hl={$language}&q={%adress}%2C%20Borl%C3%A4nge%2C%20Sverige'
  title: Google Maps Borlänge
  tags:
  - maps
  - google
  examples:
    centrum: sök centrum i Borlänge
gme/1:
  url: 'http://maps.google.com/maps?hl={$language}&q={%adress}%2C%20Eskilstuna%2C%20Sverige'
  title: Google Maps Eskilstuna
  tags:
  - maps
  - google
  examples:
    centrum: sök centrum i Eskilstuna
gmf/1:
  url: 'http://maps.google.com/maps?hl={$language}&q={%adress}%2C%20Falun%2C%20Sverige'
  title: Google Maps Falun
  tags:
  - maps
  - google
  examples:
    centrum: sök centrum i Falun
gmg/1:
  url: 'http://maps.google.com/maps?hl={$language}&q={%adress}%2C%20Gothenburg%2C%20Sverige'
  title: Google Maps Gothenburg
  tags:
  - maps
  - google
  examples:
    centrum: sök centrum i Gothenburg
gmgä/1:
  url: 'http://maps.google.com/maps?hl={$language}&q={%adress}%2C%20G%C3%A4vle%2C%20Sverige'
  title: Google Maps Gävle
  tags:
  - maps
  - google
  examples:
    centrum: sök centrum i Gävle
gmh/1:
  url: 'http://maps.google.com/maps?hl={$language}&q={%adress}%2C%20Helsingborg%2C%20Sverige'
  title: Google Maps Helsingborg
  tags:
  - maps
  - google
  examples:
    centrum: sök centrum i Helsingborg
gmha/1:
  url: 'http://maps.google.com/maps?hl={$language}&q={%adress}%2C%20Halmstad%2C%20Sverige'
  title: Google Maps Halmstad
  tags:
  - maps
  - google
  examples:
    centrum: sök centrum i Halmstad
gmj/1:
  url: 'http://maps.google.com/maps?hl={$language}&q={%adress}%2C%20J%C3%B6nk%C3%B6ping%2C%20Sverige'
  title: Google Maps Jönköping
  tags:
  - maps
  - google
  examples:
    centrum: sök centrum i Jönköping
gmk/1:
  url: 'http://maps.google.com/maps?hl={$language}&q={%adress}%2C%20Karlstad%2C%20Sverige'
  title: Google Maps Karlstad
  tags:
  - maps
  - google
  examples:
    centrum: sök centrum i Karlstad
gmkk/1:
  url: 'http://maps.google.com/maps?hl={$language}&q={%adress}%2C%20Karlskrona%2C%20Sverige'
  title: Google Maps Karlskrona
  tags:
  - maps
  - google
  examples:
    centrum: sök centrum i Karlskrona
gmkm/1:
  url: 'http://maps.google.com/maps?hl={$language}&q={%adress}%2C%20Kalmar%2C%20Sverige'
  title: Google Maps Kalmar
  tags:
  - maps
  - google
  examples:
    centrum: sök centrum i Kalmar
gmks/1:
  url: 'http://maps.google.com/maps?hl={$language}&q={%adress}%2C%20Kristianstad%2C%20Sverige'
  title: Google Maps Kristianstad
  tags:
  - maps
  - google
  examples:
    centrum: sök centrum i Kristianstad
gml/1:
  url: 'http://maps.google.com/maps?hl={$language}&q={%adress}%2C%20Link%C3%B6ping%2C%20Sverige'
  title: Google Maps Linköping
  tags:
  - maps
  - google
  examples:
    centrum: sök centrum i Linköping
gmld/1:
  url: 'http://maps.google.com/maps?hl={$language}&q={%adress}%2C%20Liding%C3%B6%2C%20Sverige'
  title: Google Maps Lidingö
  tags:
  - maps
  - google
  examples:
    centrum: sök centrum i Lidingö
gmll/1:
  url: 'http://maps.google.com/maps?hl={$language}&q={%adress}%2C%20Lule%C3%A5%2C%20Sverige'
  title: Google Maps Luleå
  tags:
  - maps
  - google
  examples:
    centrum: sök centrum i Luleå
gmlu/1:
  url: 'http://maps.google.com/maps?hl={$language}&q={%adress}%2C%20Lund%2C%20Sverige'
  title: Google Maps Lund
  tags:
  - maps
  - google
  examples:
    centrum: sök centrum i Lund
gmm/1:
  url: 'http://maps.google.com/maps?hl={$language}&q={%adress}%2C%20Malm%C3%B6%2C%20Sverige'
  title: Google Maps Malmö
  tags:
  - maps
  - google
  examples:
    centrum: sök centrum i Malmö
gmn/1:
  url: 'http://maps.google.com/maps?hl={$language}&q={%adress}%2C%20Norrk%C3%B6ping%2C%20Sverige'
  title: Google Maps Norrköping
  tags:
  - maps
  - google
  examples:
    centrum: sök centrum i Norrköping
gmna/1:
  url: 'http://maps.google.com/maps?hl={$language}&q={%adress}%2C%20Nacka%2C%20Sverige'
  title: Google Maps Nacka
  tags:
  - maps
  - google
  examples:
    centrum: sök centrum i Nacka
gmny/1:
  url: 'http://maps.google.com/maps?hl={$language}&q={%adress}%2C%20Nyk%C3%B6ping%2C%20Sverige'
  title: Google Maps Nyköping
  tags:
  - maps
  - google
  examples:
    centrum: sök centrum i Nyköping
gms/1:
  url: 'http://maps.google.com/maps?hl={$language}&q={%adress}%2C%20Stockholm%2C%20Sverige'
  title: Google Maps Stockholm
  tags:
  - maps
  - google
  examples:
    centrum: sök centrum i Stockholm
gmsb/1:
  url: 'http://maps.google.com/maps?hl={$language}&q={%adress}%2C%20Sundbyberg%2C%20Sverige'
  title: Google Maps Sundbyberg
  tags:
  - maps
  - google
  examples:
    centrum: sök centrum i Sundbyberg
gmsk/1:
  url: 'http://maps.google.com/maps?hl={$language}&q={%adress}%2C%20Skellefte%C3%A5%2C%20Sverige'
  title: Google Maps Skellefteå
  tags:
  - maps
  - google
  examples:
    centrum: sök centrum i Skellefteå
gmso/1:
  url: 'http://maps.google.com/maps?hl={$language}&q={%adress}%2C%20Solna%2C%20Sverige'
  title: Google Maps Solna
  tags:
  - maps
  - google
  examples:
    centrum: sök centrum i Solna
gmsv/1:
  url: 'http://maps.google.com/maps?hl={$language}&q={%adress}%2C%20Sundsvall%2C%20Sverige'
  title: Google Maps Sundsvall
  tags:
  - maps
  - google
  examples:
    centrum: sök centrum i Sundsvall
gmsö/1:
  url: 'http://maps.google.com/maps?hl={$language}&q={%adress}%2C%20S%C3%B6dert%C3%A4lje%2C%20Sverige'
  title: Google Maps Södertälje
  tags:
  - maps
  - google
  examples:
    centrum: sök centrum i Södertälje
gmt/1:
  url: 'http://maps.google.com/maps?hl={$language}&q={%adress}%2C%20Trollh%C3%A4ttan%2C%20Sverige'
  title: Google Maps Trollhättan
  tags:
  - maps
  - google
  examples:
    centrum: sök centrum i Trollhättan
gmu/1:
  url: 'http://maps.google.com/maps?hl={$language}&q={%adress}%2C%20Uppsala%2C%20Sverige'
  title: Google Maps Uppsala
  tags:
  - maps
  - google
  examples:
    centrum: sök centrum i Uppsala
gmum/1:
  url: 'http://maps.google.com/maps?hl={$language}&q={%adress}%2C%20Ume%C3%A5%2C%20Sverige'
  title: Google Maps Umeå
  tags:
  - maps
  - google
  examples:
    centrum: sök centrum i Umeå
gmv/1:
  url: 'http://maps.google.com/maps?hl={$language}&q={%adress}%2C%20V%C3%A4ster%C3%A5s%2C%20Sverige'
  title: Google Maps Västerås
  tags:
  - maps
  - google
  examples:
    centrum: sök centrum i Västerås
gmvx/1:
  url: 'http://maps.google.com/maps?hl={$language}&q={%adress}%2C%20V%C3%A4xj%C3%B6%2C%20Sverige'
  title: Google Maps Växjö
  tags:
  - maps
  - google
  examples:
    centrum: sök centrum i Växjö
gmä/1:
  url: 'http://maps.google.com/maps?hl={$language}&q={%adress}%2C%20%C3%84ngelholm%2C%20Sverige'
  title: Google Maps Ängelholm
  tags:
  - maps
  - google
  examples:
    centrum: sök centrum i Ängelholm
gmö/1:
  url: 'http://maps.google.com/maps?hl={$language}&q={%adress}%2C%20%C3%96rebro%2C%20Sverige'
  title: Google Maps Örebro
  tags:
  - maps
  - google
  examples:
    centrum: sök centrum i Örebro
gmös/1:
  url: 'http://maps.google.com/maps?hl={$language}&q={%adress}%2C%20%C3%96stersund%2C%20Sverige'
  title: Google Maps Östersund
  tags:
  - maps
  - google
  examples:
    centrum: sök centrum i Östersund
llt/2:
  url: 'http://stefanschramm.net/dev/postredirector/?_target=http://193.45.213.123/lulea/v2/querypage_adv.aspx?nonExistingUrlRequested=1&inpPointFr={%Fra}&inpPointTo={%Till}&cmdAction=search'
  title: Luleå Lokaltrafik
  tags:
  - travel
  - luleå
  examples:
    'sotargatan, järnvägen': Nästa buss från Sotargatan till Järnvägen
llt/3:
  url: 'http://stefanschramm.net/dev/postredirector/?_target=http://193.45.213.123/lulea/v2/querypage_adv.aspx?nonExistingUrlRequested=1&inpPointFr={%Fra}&inpPointTo={%Till}&inpTime={%Avgång}00&cmdAction=search'
  title: Luleå Lokaltrafik
  tags:
  - travel
  - luleå
  examples:
    'sotargatan, järnvägen,10': 'Buss från Sotargatan till Järnvägen, avgång kl. 10'
ltnbd/2:
  url: 'http://reseplanerare.resrobot.se/bin/query.exe/sn?L=vs_ltnbd&S={%Från}!&Z={%Till}!&start=1'
  title: Länstraffiken Norbotten
  tags:
  - travel
  - luleå
  - norbotten
  examples:
    'boden, luleå': Nästa buss från Boden till Luleå
ltnbd/3:
  url: 'http://reseplanerare.resrobot.se/bin/query.exe/sn?L=vs_ltnbd&S={%Från}!&Z={%Till}!&T={%Avgång}&start=1'
  title: Länstraffiken Norbotten
  tags:
  - travel
  - luleå
  - norbotten
  examples:
    'boden, luleå, 10': 'Buss från Boden till Luleå, avgång kl. 10'
rr/2:
  url: 'http://reseplanerare.resrobot.se/bin/query.exe/sn?S={%Från}!&Z={%Till}!&start=1'
  title: Resrobot
  tags:
  - travel
  examples:
    'stockholm, malmö': Nästa tåg från Stockholm till Malmö
rr/3:
  url: 'http://reseplanerare.resrobot.se/bin/query.exe/sn?S={%Från}!&Z={%Till}!&T={%Avgång}&start=1'
  title: Resrobot
  tags:
  - travel
  examples:
    'stockholm, malmö, 10': 'Tåg från Stockholm till Malmö, avgång kl. 10'
sl/2:
  url: 'http://reseplanerare.sl.se/bin/query.exe/sn?S={%Från}!&Z={%Till}!&start=1'
  title: Storstockholms Lokaltrafik
  tags:
  - travel
  - stockholm
  examples:
    'husby, alby': Nästa tåg från Husby till Alby
sl/3:
  url: 'http://reseplanerare.sl.se/bin/query.exe/sn?S={%Från}!&Z={%Till}!&T={%Avgång}&start=1'
  title: Storstockholms Lokaltrafik
  tags:
  - travel
  - stockholm
  examples:
    'husby, alby, 10': 'Tåg från Husby till Alby, avgång kl. 10'
sl/4:
  url: 'http://reseplanerare.sl.se/bin/query.exe/sn?S={%Från}!&Z={%Till}!&T={%Avgång}&D={%Dag}&start=1'
  title: Storstockholms Lokaltrafik
  tags:
  - travel
  - stockholm
  examples:
    'husby, alby, 10, 30.12.': 'Tåg från Husby till Alby, avgång kl. 10, dag 30.12.'
srse/1:
  url: 'http://sverigesradio.se/sida/sok.aspx?q={%programmets namn}&sort=relevance'
  title: Sveriges radio search
  tags:
  - radio
  - sweden
  examples:
    stockholm: Search for "stockholm".
zal/1:
  url: 'http://www.zalando.se/katalog/?q={%produkt}'
  title: Zalando.se
  tags:
  - shopping
  - zalando
  examples:
    kläder: söka kläder
