blocket 1:
  url: http://www.blocket.se/li?q={%query}
  title: Blocket.se
  tags:
  - shopping
  - blocket
  examples:
    iphone: Search for "iphone"
gm 2:
  url: https://www.google.com/maps/search/{%stad|type=city}%2C%20{%gata}%2C%20Sverige/?hl={$language}
  title: Google Maps Sverige
  tags:
  - maps
  - google
  examples:
    s, centrum: sök centrum i Stockholm
    lu, centrum: sök centrum i Lund
llt 2:
  url: http://stefanschramm.net/dev/postredirector/?_target=http://193.45.213.123/lulea/v2/querypage_adv.aspx?nonExistingUrlRequested=1&inpPointFr={%Fra}&inpPointTo={%Till}&cmdAction=search
  title: Luleå Lokaltrafik
  tags:
  - travel
  - luleå
  examples:
    sotargatan, järnvägen: Nästa buss från Sotargatan till Järnvägen
llt 3:
  url: http://stefanschramm.net/dev/postredirector/?_target=http://193.45.213.123/lulea/v2/querypage_adv.aspx?nonExistingUrlRequested=1&inpPointFr={%Fra}&inpPointTo={%Till}&inpTime={%Avgång}00&cmdAction=search
  title: Luleå Lokaltrafik
  tags:
  - travel
  - luleå
  examples:
    sotargatan, järnvägen,10: Buss från Sotargatan till Järnvägen, avgång kl. 10
ltnbd 2:
  url: http://reseplanerare.resrobot.se/bin/query.exe/sn?L=vs_ltnbd&S={%Från}!&Z={%Till}!&start=1
  title: Länstraffiken Norbotten
  tags:
  - travel
  - luleå
  - norbotten
  examples:
    boden, luleå: Nästa buss från Boden till Luleå
ltnbd 3:
  url: http://reseplanerare.resrobot.se/bin/query.exe/sn?L=vs_ltnbd&S={%Från}!&Z={%Till}!&T={%Avgång}&start=1
  title: Länstraffiken Norbotten
  tags:
  - travel
  - luleå
  - norbotten
  examples:
    boden, luleå, 10: Buss från Boden till Luleå, avgång kl. 10
rr 2:
  url: http://reseplanerare.resrobot.se/bin/query.exe/sn?S={%Från}!&Z={%Till}!&start=1
  title: Resrobot
  tags:
  - travel
  examples:
    stockholm, malmö: Nästa tåg från Stockholm till Malmö
rr 3:
  url: http://reseplanerare.resrobot.se/bin/query.exe/sn?S={%Från}!&Z={%Till}!&T={%Avgång}&start=1
  title: Resrobot
  tags:
  - travel
  examples:
    stockholm, malmö, 10: Tåg från Stockholm till Malmö, avgång kl. 10
sl 2:
  url: http://reseplanerare.sl.se/bin/query.exe/sn?S={%Från}!&Z={%Till}!&start=1
  title: Storstockholms Lokaltrafik
  tags:
  - travel
  - stockholm
  examples:
    husby, alby: Nästa tåg från Husby till Alby
sl 3:
  url: http://reseplanerare.sl.se/bin/query.exe/sn?S={%Från}!&Z={%Till}!&T={%Avgång}&start=1
  title: Storstockholms Lokaltrafik
  tags:
  - travel
  - stockholm
  examples:
    husby, alby, 10: Tåg från Husby till Alby, avgång kl. 10
sl 4:
  url: http://reseplanerare.sl.se/bin/query.exe/sn?S={%Från}!&Z={%Till}!&T={%Avgång}&D={%Dag}&start=1
  title: Storstockholms Lokaltrafik
  tags:
  - travel
  - stockholm
  examples:
    husby, alby, 10, 30.12.: Tåg från Husby till Alby, avgång kl. 10, dag 30.12.
srse 1:
  url: http://sverigesradio.se/sida/sok.aspx?q={%programmets namn}&sort=relevance
  title: Sveriges radio search
  tags:
  - radio
  - sweden
  examples:
    stockholm: Search for "stockholm".
zal 1:
  url: http://www.zalando.se/katalog/?q={%produkt}
  title: Zalando.se
  tags:
  - shopping
  - zalando
  examples:
    kläder: söka kläder
