e 0:
  url: 'http://www.ebay.com.sg/'
  title: Ebay.com.sg
  tags:
  - shopping
  - ebay
e 1:
  url: 'http://www.ebay.com.sg/sch/i.html?_nkw={%query}'
  title: Ebay.com.sg
  tags:
  - shopping
  - ebay
  examples:
    smartphone: Search for "smartphone"
