cp 2:
  url: https://cp.hnonline.sk/vlakbusmhd/spojenie/?f={%odkiaľ|type=city}&t={%kam|type=city}&submit=1&pt=true
  title: Cestovné poriadky
  tags:
  - bus
  - cp
  - train
  - travel
  examples:
    bratislava, košice: Vlak alebo bus z Bratislavy do Košić
cp 3:
  url: https://cp.hnonline.sk/vlakbusmhd/spojenie/?f={%odkiaľ|type=city}&t={%kam|type=city}&time={%čas|type=time|output=HH:mm}&submit=1&pt=true
  title: Cestovné poriadky
  tags:
  - bus
  - cp
  - train
  - travel
  examples:
    bratislava, košice: Vlak alebo bus z Bratislavy do Košić o 20:00h
cp 4:
  url: https://cp.hnonline.sk/vlakbusmhd/spojenie/?f={%odkiaľ|type=city}&t={%kam|type=city}&time={%čas|type=time|output=HH:mm}&date={%datum|type=date|output=DD.MM.YYYY}&submit=1&pt=true
  title: Cestovné poriadky
  tags:
  - bus
  - cp
  - train
  - travel
  examples:
    bratislava, košice: Vlak alebo bus z Bratislavy do Košić o 20:00h 10.12.
gm 2:
  url: https://www.google.com/maps/search/{%mesto|type=city}%2C%20{%adresa}%2C%20Slovensko/?hl={$language}
  title: Google Maps Slovensko
  tags:
  - google
  - maps
  examples:
    ba, hlavná: Ukáž Hlavná v meste Bratislava
    ke, hlavná: Ukáž Hlavná v meste Košice
zsr 2:
  url: https://www.zsr.sk/pre-cestujucich/vlakove-spojenia-elis/?hladajSpoj=true&txtFrom={%odkiaľ|type=city}&txtTo={%kam|type=city}
  title: Vlakové spojenia ŽSR
  tags:
  - railway
  - travel
  - zsr
  - zssk
  examples:
    ba, ke: Spojenie z Brastislavy do Košíc teraz
zsr 3:
  url: https://www.zsr.sk/pre-cestujucich/vlakove-spojenia-elis/?hladajSpoj=true&txtFrom={%odkiaľ|type=city}&txtTo={%kam|type=city}&txtTime={%čas|type=time}
  title: Vlakové spojenia ŽSR
  tags:
  - railway
  - travel
  - zsr
  - zssk
  examples:
    ba, ke, 10: Spojenie z Brastislavy do Košíc v 10 hod.
zsr 4:
  url: https://www.zsr.sk/pre-cestujucich/vlakove-spojenia-elis/?hladajSpoj=true&txtFrom={%odkiaľ|type=city}&txtTo={%kam|type=city}&txtTime={%čas|type=time}&txtDate={%dátum|type=date}
  title: Vlakové spojenia ŽSR
  tags:
  - railway
  - travel
  - zsr
  - zssk
  examples:
    ba, ke, 10, 31.1.: Spojenie z Brastislavy do Košíc v 10 hod. 31. januára
