name: Build and Deploy
on:
  push:
    branches:
      - master
      - 173-move-documentation-to-this-future-monorepo
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Replace with your Python version
    - name: Cache Pipenv virtualenv
      uses: actions/cache@v2
      with:
        path: ~/.local/share/virtualenvs
        key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pipenv-

    - name: Install dependencies
      run: |
        pip install pipenv
        pipenv install

    - name: Build MkDocs site
      run: |
        pipenv run mkdocs build
      - uses: actions/setup-node@v4
        with:
          node-version: 21
      - run: npm clean-install
      - run: npm run build
      - run: npm run test-unit
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/public/
          repository-name: trovu/trovu.github.io
          branch: master
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          # Either to "master" or "dev", depending on the branch.
          target-folder: ${{ (github.ref == 'refs/heads/master' && 'master') || 'dev' }}
          clean: true
