name: Cypress Tests
# Disable for now, as long as
# baseUrl: 'http://127.0.0.1:8081/',
# in cypress.config.js is not fixed.
#
# on:
#   push:
#     branches: [$default-branch, '*']
#   pull_request:
#     branches: [$default-branch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test
